### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by msslava** [ukfast/gitlab-registry-cleanup#4]
Hi, thanks for sharing, very useful tool!
Recently, I had a problem, about a month ago.
The error occurs on the policy
```
- name: general
  filter:
    include: .*
    exclude: ^(master|develop|staging-preprod|staging-testing|stage).+
    keep: 30
    age: 60
```

debug info:
```
DEBU[1412] IncludeFilter: Including matched tag task-test-ingress_c446f18f
DEBU[1412] IncludeFilter: Including matched tag task-test-ingress_f0401c3a
DEBU[1412] IncludeFilter: Including matched tag task-test-ingress_latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x428068]

goroutine 1 [running]:
github.com/ukfast/gitlab-registry-cleanup/pkg/filter.OrderedFilter.func1(0x242, 0x241, 0x0)
	/build/pkg/filter/filter.go:108 +0x38
sort.insertionSort_func(0x400008b078, 0x40002eeae0, 0x230, 0x244)
	/usr/local/go/src/sort/zfuncversion.go:12 +0xb0
sort.stable_func(0x400008b078, 0x40002eeae0, 0x367)
	/usr/local/go/src/sort/zfuncversion.go:167 +0x48
sort.SliceStable(0x48ca60, 0x40002eeac0, 0x400008b078)
	/usr/local/go/src/sort/slice.go:27 +0xbc
github.com/ukfast/gitlab-registry-cleanup/pkg/filter.OrderedFilter(0x4000474000, 0x367, 0x400, 0x4000025248, 0x2, 0x4000154420, 0x23, 0x1e, 0x3c, 0x4000474000, ...)
	/build/pkg/filter/filter.go:107 +0x84
github.com/ukfast/gitlab-registry-cleanup/pkg/filter.(*FilterPipeline).Execute(0x400008b3c0, 0x400008b390, 0x6, 0x6, 0x1, 0x18, 0x0, 0x0, 0x0)
	/build/pkg/filter/filter.go:31 +0xb4
github.com/ukfast/gitlab-registry-cleanup/cmd.processRepositoryProjectPolicy(0x4000168a00, 0x400000a300, 0x40004d7fc0, 0xc13, 0x4000025224, 0x7, 0x4000025248, 0x2, 0x4000154420, 0x23, ...)
	/build/cmd/execute.go:256 +0x780
github.com/ukfast/gitlab-registry-cleanup/cmd.processRepositoryProjectPolicies(0x4000168a00, 0x400000a300, 0x400001eaf0, 0x40004d7fc0, 0x0, 0x1519, 0x0, 0x0, 0x0, 0x0, ...)
	/build/cmd/execute.go:211 +0x274
github.com/ukfast/gitlab-registry-cleanup/cmd.processRepositoryProjects(0x4000168a00, 0x400000a300, 0x400001eaf0, 0x0, 0x1519, 0x0, 0x0, 0x0, 0x0, 0x400018c5a0, ...)
	/build/cmd/execute.go:159 +0x1fc
github.com/ukfast/gitlab-registry-cleanup/cmd.processRepositoryConfig(0x4000168a00, 0x400000a300, 0x4000324000, 0x163, 0x200, 0x400001eaf0, 0x0, 0x1519, 0x0, 0x0, ...)
	/build/cmd/execute.go:75 +0x2a8
github.com/ukfast/gitlab-registry-cleanup/cmd.executeCleanup(0x4000168a00, 0x400006fef0, 0x0, 0x3, 0x0, 0x0)
	/build/cmd/execute.go:51 +0x358
github.com/ukfast/gitlab-registry-cleanup/cmd.ExecuteCmd.func1(0x4000168a00, 0x400006fef0, 0x0, 0x3, 0x0, 0x0)
	/build/cmd/execute.go:20 +0x40
github.com/spf13/cobra.(*Command).execute(0x4000168a00, 0x400006fe90, 0x3, 0x3, 0x4000168a00, 0x400006fe90)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x30c
github.com/spf13/cobra.(*Command).ExecuteC(0x8f4900, 0x434bc, 0x4000080058, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x274
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/ukfast/gitlab-registry-cleanup/cmd.Execute(...)
	/build/cmd/root.go:18
main.main()
	/build/main.go:10 +0x34
```

**Comment by 0x4c6565** [comment]
Hi @msslava,

Nil pointer dereference is happening here:

```
return filteredTags[i].CreatedAt.Before(*filteredTags[j].CreatedAt)
```
The `created_at` field being returned from the Gitlab API for at least one of the tags will be null. We can put a workaround in to the sort function callback, but would be good to check whether there are any issues with any of the tags in your Gitlab instance?

**Comment by msslava** [comment]
Hi, @0x4c6565! Thanks for the info, I will check it right now

**Comment by msslava** [comment]
I ran a small script on all tags in my repository:

```
for tag in $(./regctl tag ls $MY_REGISTRY); do
  echo $tag was created at - $(./regctl image config $MY_REGISTRY:$tag --format "{{ .Created }}" --verbosity error 2> /dev/null)
done
```
and I found that one of the tags was missing a creation date.
I removed this tag and try to run gitlab-registry-cleanup again

**Comment by msslava** [comment]
It looks like that was the problem, thanks!
It would also be cool to add the functionality of retry when deleting.
For example,

`level=error msg="Failed to process repository: %sFailed to process repository config projects: Failed to remove tag`

Gitlab API is a very weak point that often fails
